package pwd4llm

/** Denotes whether an evaluator is successful or not.
  */
enum EvalResult[R] {

  /** Denotes successful evaluation.
    *
    * @param result
    *   is the output of the parser, after successfully parsing
    */
  case Success(result: R)

  /** Denotes failed evalution.
    *
    * @param partial_result
    *   is some partial output of a parser generated in the evaluation process,
    *   that may be used for debugging
    */
  case Failure(partial_result: R)

  /** Denotes an evaluation is failed due to illegal actions generated by the
    * token generator, like deleting the last token from an already empty input.
    */
  case CriticalFailure()
}

import EvalResult.*

/** The Evaluator searches for a parse input generated by a TokenGenerator that
  * a given Parser succeeds on.
  */
trait Evaluator {

  /** Let's the evaluator run on a parser and token generator.
    *
    * @param p
    *   is the Parser validating the inputs
    * @param g
    *   is the TokenGenerator generating inputs
    * @return
    *   an evaluation result, depending on succession or failure
    */
  def eval[T, R, G <: TokenGenerator[T]](p: Parser[T, R], g: G): EvalResult[R]
}

import pwd4llm.ParserState.*
import pwd4llm.GeneratorAction.*

/** An evaluator that uses a stack in the evaluation process to store each
  * intermediate parser produced by feeding tokens into it.
  */
object StackEvaluator extends Evaluator {

  import scala.collection.mutable.Stack

  def eval[T, R, G <: TokenGenerator[T]](
      p: Parser[T, R],
      g: G
  ): EvalResult[R] = {
    val history: Stack[Parser[T, R]] = Stack()
    val initial = p

    def feed(p: Parser[T, R], t: T) = {
      history.push(p)
      p.feed(t)
    }

    def feedAll(p: Parser[T, R], ts: Iterator[T]) =
      ts.foldLeft(p)((p, t) => feed(p, t))

    def go(p: Parser[T, R]): EvalResult[R] = {
      g.receiveFeedback(p.state)
      val a = g.suggest()

      a match {
        case Concatenate(ts) => go(feedAll(p, ts))
        case Append(t)       => go(feed(p, t))
        case DropLast(n) => {
          history.dropInPlace(n - 1)
          val x =
            try history.pop()
            catch case _ => initial
          go(x)
        }
        case DeleteLast() => {
          val x =
            try history.pop()
            catch case _ => return CriticalFailure()
          go(x)
        }
        case ReplaceLast(t) => {
          val x =
            try history.pop()
            catch case _ => return CriticalFailure()
          go(feed(x, t))
        }
        case Rebuild(ts) => {
          history.clear()
          go(feedAll(initial, ts))
        }
        case Reset() => {
          history.clear()
          go(initial)
        }
        case Finish() =>
          if p.state == Accepting then Success(p.results)
          else Failure(p.results)
      }
    }

    go(initial)
  }
}

/** An evaluator that uses a stack in the evaluation process to store each token
  * in the currently relevant input. It always parses all tokens anew, if
  * deleting tokens of the current input is required, never remembering previous
  * parsers. In other words, it then scraps all the process and starts from the
  * start.
  */
object ScrapAllEvaluator extends Evaluator {

  import scala.collection.mutable.Stack

  def eval[T, R, G <: TokenGenerator[T]](
      p: Parser[T, R],
      g: G
  ): EvalResult[R] = {
    val history: Stack[T] = Stack()
    val initial = p

    def feed(p: Parser[T, R], t: T) = {
      history.push(t)
      p.feed(t)
    }

    def feedAll(p: Parser[T, R], ts: Iterator[T]) =
      ts.foldLeft(p)((p, t) => feed(p, t))

    def pureFeedAll(p: Parser[T, R], ts: Iterator[T]) =
      ts.foldLeft(p)((p, t) => p.feed(t)) // does not modify stack

    def go(p: Parser[T, R]): EvalResult[R] = {
      g.receiveFeedback(p.state)
      val a = g.suggest()

      a match {
        case Concatenate(ts) => go(feedAll(p, ts))
        case Append(t)       => go(feed(p, t))
        case DropLast(n) =>
          go(pureFeedAll(initial, history.dropInPlace(n).reverseIterator))
        case DeleteLast() => {
          try history.pop()
          catch case _ => return CriticalFailure()
          go(pureFeedAll(initial, history.reverseIterator))
        }
        case ReplaceLast(t) => {
          try history.pop()
          catch case _ => return CriticalFailure()
          history.push(t)
          go(pureFeedAll(initial, history.reverseIterator))
        }
        case Rebuild(ts) => {
          history.clear()
          go(feedAll(initial, ts))
        }
        case Reset() => {
          history.clear()
          go(initial)
        }
        case Finish() =>
          if p.state == Accepting then Success(p.results)
          else Failure(p.results)
      }
    }

    go(initial)
  }
}

/** An evaluator that uses a stack in the evaluation process to store each
  * parser generated by the last action. Meaning, in case of deleting tokens, if
  * a parser state is required that does not go as far as the last action (i.e.
  * deleting last token after appending 20 tokens), then the tokens inbetween
  * will be parsed anew.
  */
object RememberActionEvaluator extends Evaluator {

  import scala.collection.mutable.Stack

  def eval[T, R, G <: TokenGenerator[T]](
      p: Parser[T, R],
      g: G
  ): EvalResult[R] = {
    val parser_history: Stack[(Int, Parser[T, R])] = Stack()
    val token_history: Stack[T] = Stack()
    val initial = p

    def feed(p: Parser[T, R], t: T) = {
      parser_history.push((1, p))
      p.feed(t)
    }

    def feedAll(p: Parser[T, R], ts: Iterator[T]) = {
      var (cur, lst, len) = ts.nextOption() match {
        case Some(x) => (p.feed(x), x, 1)
        case _       => return p
      }

      for t <- ts do {
        token_history.push(lst)
        len += 1
        lst = t
        cur = cur.feed(t)
      }

      parser_history.push((len, p))

      cur
    }

    def pureFeedAll(p: Parser[T, R], ts: Iterator[T]) =
      ts.foldLeft(p)((p, t) => p.feed(t))

    // Unsafely build the parser state correlating to deleting one token (can throw exception)
    def pop() = {
      val (n, x) = parser_history.pop()
      val diff = n - 1
      if diff == 0 then return x
      val y = pureFeedAll(x, token_history.take(diff))
      token_history.dropInPlace(diff)
      parser_history.push((diff, y))
      y
    }

    // Unsafely build the parser state correlating to deleting >1 tokens (can throw exception)
    def dropLast(m: Int) = {
      var k = m
      var cur = parser_history.pop()
      while cur._1 < k do {
        k -= cur._1
        cur = parser_history.pop()
      }

      val (n, x) = cur
      val diff = n - k
      if diff == 0 then return x
      val y = pureFeedAll(x, token_history.take(diff))
      token_history.dropInPlace(diff)
      parser_history.push((diff, y))
      y
    }

    def go(p: Parser[T, R]): EvalResult[R] = {
      g.receiveFeedback(p.state)
      val a = g.suggest()

      a match {
        case Concatenate(ts) => go(feedAll(p, ts))
        case Append(t)       => go(feed(p, t))
        case DropLast(n) => {
          val x =
            try dropLast(n)
            catch case _ => return CriticialFailure()
          go(x)
        }
        case DeleteLast() => {
          val x =
            try pop()
            catch case _ => return CriticialFailure()
          go(x)
        }
        case ReplaceLast(t) => {
          val x =
            try pop()
            catch case _ => return CriticialFailure()
          go(feed(x, t))
        }
        case Rebuild(ts) => {
          parser_history.clear()
          token_history.clear()
          go(feedAll(initial, ts))
        }
        case Reset() => {
          parser_history.clear()
          token_history.clear()
          go(initial)
        }
        case Finish() =>
          if p.state == Accepting then Success(p.results)
          else Failure(p.results)
      }
    }

    go(initial)
  }
}
