package pwd4llm

/** Denotes whether an evaluator is successful or not.
  */
enum EvalResult[R] {

  /** Denotes successful evaluation.
    *
    * @param result
    *   is the output of the parser, after successfully parsing
    */
  case Success(result: R)

  /** Denotes failed evalution.
    *
    * @param partial_result
    *   is some partial output of a parser generated in the evaluation process,
    *   that may be used for debugging
    */
  case Failure(partial_result: R)

  /** Denotes an evaluation is failed due to illegal actions generated by the
    * token generator, like deleting the last token from an already empty input.
    */
  case CriticalFailure()
}

import EvalResult.*

/** The Evaluator searches for a parse input generated by a TokenGenerator that
  * a given Parser succeeds on.
  */
trait Evaluator {

  /** Let's the evaluator run on a parser and token generator.
    *
    * @param p
    *   is the Parser validating the inputs
    * @param g
    *   is the TokenGenerator generating inputs
    * @return
    *   an evaluation result, depending on succession or failure
    */
  def eval[T, R, G <: TokenGenerator[T]](p: Parser[T, R], g: G): EvalResult[R]
}

import pwd4llm.ParserStatus.*
import pwd4llm.GeneratorAction.*

object StackEvaluator extends Evaluator {

  import scala.collection.mutable.Stack

  def eval[T, R, G <: TokenGenerator[T]](
      p: Parser[T, R],
      g: G
  ): EvalResult[R] = {
    val history: Stack[Parser[T, R]] = Stack()
    val initial = p

    def feed(p: Parser[T, R], t: T) = {
      history.push(p)
      p.feed(t)
    }

    def feedAll(p: Parser[T, R], ts: Iterator[T]) =
      ts.foldLeft(p)((p, t) => feed(p, t))

    def go(p: Parser[T, R]): EvalResult[R] = {
      g.receiveFeedback(p.status)
      val a = g.suggest()

      a match {
        case Concatenate(ts) => go(feedAll(p, ts))
        case Append(t)       => go(feed(p, t))
        case DeleteLast() => {
          val x =
            try history.pop()
            catch case _ => return CriticalFailure()
          go(x)
        }
        case ReplaceLast(t) => {
          val x =
            try history.pop()
            catch case _ => return CriticalFailure()
          go(feed(x, t))
        }
        case Rebuild(ts) => {
          history.clear()
          go(feedAll(initial, ts))
        }
        case Reset() => {
          history.clear()
          go(initial)
        }
        case Finish() =>
          p.status match {
            case Accepting => Success(p.results)
            case _         => Failure(p.results)
          }
      }
    }

    go(initial)
  }
}

object ScrapAllEvaluator extends Evaluator {

  import scala.collection.mutable.Stack

  def eval[T, R, G <: TokenGenerator[T]](
      p: Parser[T, R],
      g: G
  ): EvalResult[R] = {
    val history: Stack[T] = Stack()
    val initial = p

    def feed(p: Parser[T, R], t: T) = {
      history.push(t)
      p.feed(t)
    }

    def feedAll(p: Parser[T, R], ts: Iterator[T]) =
      ts.foldLeft(p)((p, t) => feed(p, t))

    def pureFeedAll(p: Parser[T, R], ts: Iterator[T]) =
      ts.foldLeft(p)((p, t) => p.feed(t)) // does not modify stack

    def go(p: Parser[T, R]): EvalResult[R] = {
      g.receiveFeedback(p.status)
      val a = g.suggest()

      a match {
        case Concatenate(ts) => go(feedAll(p, ts))
        case Append(t)       => go(feed(p, t))
        case DeleteLast() => {
          try history.pop()
          catch case _ => return CriticalFailure()
          go(pureFeedAll(initial, history.reverseIterator))
        }
        case ReplaceLast(t) => {
          try history.pop()
          catch case _ => return CriticalFailure()
          go(feed(pureFeedAll(initial, history.reverseIterator), t))
        }
        case Rebuild(ts) => {
          history.clear()
          go(feedAll(initial, ts))
        }
        case Reset() => {
          history.clear()
          go(initial)
        }
        case Finish() =>
          p.status match {
            case Accepting => Success(p.results)
            case _         => Failure(p.results)
          }
      }
    }

    go(initial)
  }
}
